[environment]
TEST = "hello"

[run]
f = { filetype = "bash", command = "find . -name '*.py' | wc -l"}
lua = { filetype = "lua", file = "examples/main.lua" }
py = { filetype = "python", file = "examples/main.py" }
js = { filetype = "javascript", file = "examples/index.js" }

[run.pyt]
filetype = "python"
environment = { "Dev" = "D", "KEY" = "K" }
command = """
import os
import dev

build = {
    'version': dev.get_version(),
    'dir': dev.get_work_dir(),
    'steps': [],
    'environment': {
      'TEST': os.environ.get("TEST", "TEST not here"),
      'DEV': os.environ.get("Dev", "DEV not here"),
      'KEY': os.environ.get("KEY", "KEY not here"),
    },
}
"""

[run.luat]
filetype = "lua"
command = """
M = {}

M.init = function()
  return "init"
end

M.Out = {
  version = dev:get_version(),
  dir = dev:get_dir(),
  environment = {
    TEST = os.getenv("TEST"),
    Key = os.getenv("KEY"),
  },
  steps = {
  },
}

return M
"""

[run.sht]
filetype = "zsh"
command = "echo $TEST"

[repos.repo_2]
name = "repo_2"
path = "tests/repo_2"

[repos.repo_1]
name = "repo_1"
path = "tests/repo_1"

[repos.dev-cli]
name = "dev-cli"
path = "."
