[run]
f = { filetype = "bash", command = "find . -name '*.py' | wc -l"}
lua = { filetype = "lua", file = "examples/main.lua" }
py = { filetype = "python", file = "examples/main.py" }
js = { filetype = "javascript", file = "examples/index.js" }

[run.pyt]
filetype = "python"
command = """
import dev

build = {
    'version': dev.get_version(),
    'dir': dev.get_work_dir(),
    'steps': [],
}
"""

[run.sht]
filetype = "zsh"
deps = ["f"]
command = """
echo one: $1 two: $2 three: $3
read -p "Switch[Ss]/Boot[Bb] " -r
if [[ $REPLY =~ ^[Ss] ]]; then
  echo "Switching"
elif [[ $REPLY =~ ^[Bb] ]]; then
  echo "Booting"
else
  echo "Cancelled"
fi
"""

[repos.repo_2]
name = "repo_2"
path = "tests/repo_2"

[repos.repo_1]
name = "repo_1"
path = "tests/repo_1"

[repos.dev-cli]
name = "dev-cli"
path = "."
