[run]
try = { filetype = "bash", command = "find . -name '*.py' | wc -l"}
lua = { filetype = "lua", file = "examples/init.lua" }
py = { filetype = "python", file = "examples/main.py" }
js = { filetype = "javascript", file = "examples/index.js" }

[repos.repo_2]
name = "repo_2"
path = "tests/repo_2"

[repos.repo_1]
name = "repo_1"
path = "tests/repo_1"

[repos.graphql-tests]
org = "andrewkreuzer"
name = "graphql-tests"
url = "git@github.com:andrewkreuzer/graphql-tests"
path = "tests/graphql-tests"

[repos.dev-cli]
name = "dev-cli"
path = "."
